---
- name: Learning about line in line
  hosts: futurama
  gather_facts: yes

  tasks:
           - name: putting a line
             lineinfile:
                            regex: ^app11
                            line: ritten apple
                            path: ~/qwert.txt
                            create: yes
                            backup: yes
                            backrefs: yes
