---
- name : playing with variable
  hosts: futurama
  gather_facts: yes

  vars:
         juniperpw: qwerty
  tasks:
         - name: learning
           debug: 
                  var: ansible_distribution

         - name: create a new file
           file:
                 path: "~/{{juniperpw}}"
                 state: touch
