---
- name: My First playbook
  hosts: futurama
  gather_facts: yes

  tasks:
          - name: create a file
            file:
                    path: ~/sshworkedansible.txt
                    state: touch

